apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: heshambr/green-learning-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "250Mi"
            limits:
              memory: "2Gi"
              ephemeral-storage: "500Mi"
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service.dbnamespace.svc.cluster.local:5432/greenLLLLLearning
        - name: SPRING_DATASOURCE_USERNAME
          value: postgres
        - name: SPRING_DATASOURCE_PASSWORD
          value: "1010"
        - name: APP_ALLOWED_ORIGIN
          value: "http://34.31.216.009"
