name: Backend CI Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Esta etapa garante que o código seja clonado

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build the project with Maven
        run: mvn clean install

      - name: Run unit tests