name: Backend CI Pipeline

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'openjdk'
          java-package: jdk
          architecture: x64

      - name: Build the project with Maven
        run: mvn clean install -DskipTests  

      - name: Run unit tests
        run: mvn test  

      - name: Docker build and push
        run: |
          docker build -t backend .
          docker run -d --name backend-container backend
        
      - name: Check test results
        run: |
          # Exibe os resultados dos testes, caso existam falhas
          tail -n 10 target/test-classes/*.log
