name: Deploy Backend to GKE

on:
  push:
    branches: ["developer"]

env:
  PROJECT_ID: corded-racer-455623-i7
  CLUSTER_NAME: semanal-homol
  CLUSTER_LOCATION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Instalar Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Acessar cluster GKE
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --region $CLUSTER_LOCATION --project $PROJECT_ID

      - name: Disable gke-gcloud-auth-plugin
        run: |
          gcloud config unset auth/use_gke_gcloud_auth_plugin || true

      - name: Aplicar arquivos do Kubernetes
        run: |
          kubectl apply -f K8s/ --validate=false
